name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - staging
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to deploy to"
        required: true
        default: "staging"
        type: choice
        options:
          - staging
          - production

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Get Environment
        run: |
          BRANCH=${GITHUB_REF#refs/heads/}
          echo "Current branch: $BRANCH"
          if [ "$BRANCH" = "main" ]; then
            echo "DEPLOY_ENV=production" >> $GITHUB_ENV
          else
            echo "DEPLOY_ENV=staging" >> $GITHUB_ENV
          fi
          echo "Will deploy to $DEPLOY_ENV environment"

      - name: Clone or update repository
        run: |
          REPO_DIR=$HOME/repo
          if [ -d "$REPO_DIR" ]; then
            echo "Updating existing repository"
            cd $REPO_DIR
            git fetch
            git checkout $GITHUB_REF_NAME
            git pull
          else
            echo "Cloning repository"
            git clone https://github.com/brian-gates/resume.git $REPO_DIR
            cd $REPO_DIR
            git checkout $GITHUB_REF_NAME
          fi
          echo "Using commit: $(git rev-parse HEAD)"

      - name: Install dependencies
        run: |
          cd $HOME/repo
          which node || echo "Node not found"
          node --version || echo "Node version unavailable"
          npm --version || echo "NPM version unavailable"
          npm install -g pnpm
          pnpm i

      - name: Build application
        run: |
          cd $HOME/repo
          pnpm build

      - name: Deploy with PM2
        run: |
          cd $HOME/repo
          if [ "$DEPLOY_ENV" = "staging" ]; then
            echo "Deploying to STAGING on port 3001"
            pm2 restart ecosystem.config.js --env staging
          else
            echo "Deploying to PRODUCTION on port 3000"
            pm2 restart ecosystem.config.js
          fi
          echo "Deployment complete to $DEPLOY_ENV environment"
