name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - staging
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to deploy to"
        required: true
        default: "staging"
        type: choice
        options:
          - staging
          - production

jobs:
  build-and-deploy:
    runs-on: self-hosted
    environment: ${{ github.event.inputs.environment || (github.ref == 'refs/heads/main' && 'production' || 'staging') }}

    steps:
      - name: Checkout repository
        run: |
          if [ -d "repo" ]; then
            cd repo
            git pull
          else
            git clone https://github.com/brian-gates/resume.git repo
            cd repo
          fi

      - name: Set environment variable
        run: |
          echo "ENV=${{ github.event.inputs.environment || (github.ref == 'refs/heads/main' && 'production' || 'staging') }}" >> $GITHUB_ENV

      - name: Install dependencies
        run: |
          cd repo
          npm install -g pnpm
          pnpm i

      - name: Build application
        run: |
          cd repo
          pnpm build

      - name: Deploy
        run: |
          cd repo
          if [ "$ENV" = "staging" ]; then
            pm2 restart ecosystem.config.js --env staging
          else
            pm2 restart ecosystem.config.js
          fi
          echo "Deployed to $ENV environment"
